####################
#      FONTS       #
####################

# font_family				ComicShannsMono Nerd Font
# font_family				CodeNewRoman Nerd Font
# font_family				Agave Nerd Font
# font_family				BlexMono Nerd Font
# font_family				FantasqueSansM Nerd Font
# font_family				Lekton Nerd Font
font_family				Lilex Nerd Font Mono
# font_family				FiraCode Nerd Font
# font_family				Hasklug Nerd Font
# font_family				SpaceMono Nerd Font Mono
# font_family				Source Code Pro
# font_family				Hack Nerd Font
# font_family				Ubuntu Sans

bold_font				auto
italic_font			    auto
bold_italic_font		auto
font_size			    12
modify_font cell_height	130%


#######################################
# WINDOW SPLITTING & WINDOW SELECTION #
#######################################
# Create new window in current working directory
map alt+enter 			new_window_with_cwd
map ctrl+t 				new_tab_with_cwd

# Move between windows
map alt+o 				next_window
# map cmd+p	  		  previous_window
map ctrl+d 				close_window

# hide_window_decorations titlebar-only
hide_window_decorations yes
draw_minimal_borders	yes

# background_opacity 0.9
# background_blur 40


####################
#     TAB BAR      #
####################
tab_bar_edge			bottom
tab_bar_margin_width	1.0
tab_bar_margin_height	1.0 1.0
tab_bar_align			left
tab_bar_style			fade
tab_fade 0.25 0.5 0.75 1
tab_title_template "{index}: {title[title.rfind('/')+1:]}"

# oceanicnext
# active_tab_background   #1b2b30
# inactive_tab_background   #1b2b30
# active_tab_foreground   #4dfed2
# active_tab_foreground   #118B50
#
# substrata
# active_tab_background  #191c25
# inactive_tab_background  #191c25
# active_tab_foreground  #a8adb5
#
# darcula
# active_tab_background  #303030
# inactive_tab_background  #303030
# active_tab_foreground  #a8adb5
#
# poimandres
# active_tab_background  #1b1e28
# inactive_tab_background #1b1e28
# active_tab_foreground  #a8adb5
#
# ubuntu
active_tab_background  #2c001e
inactive_tab_background  #2c001e
active_tab_foreground  #aea79f
inactive_tab_foreground #77216f

####################
#       BELL       #
####################
enable_audio_bell		no


# BEGIN_KITTY_THEME
# Ubuntu
include current-theme.conf
# END_KITTY_THEME


